# golangci-lint v2 configuration for go-test-logger
version: "2"

run:
  timeout: 5m

linters:
  default: standard

  settings:
    staticcheck:
      # ST1001: Allow dot imports - this is a test utility library that uses Gomega
      checks: ["all", "-ST1001"]

  exclusions:
    paths:
      - examples
    rules:
      # Tests may skip error checks for brevity
      - path: _test\.go
        linters:
          - errcheck
